-- Müller App · Supabase (plan gratuito)
-- Ejecuta esto en SQL Editor.
-- Si ya tenías versión anterior, este script amplía con economía segura por RPC.

-- ------------------------------
-- Perfiles
-- ------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users on delete cascade,
  display_name text,
  updated_at timestamptz default now()
);

alter table public.profiles enable row level security;

drop policy if exists "profiles_select_all" on public.profiles;
create policy "profiles_select_all"
  on public.profiles for select
  using (true);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
  on public.profiles for insert
  with check ((select auth.uid()) = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles for update
  using ((select auth.uid()) = id);

create or replace function public.muller_handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name, updated_at)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'display_name', 'Estudiante'),
    now()
  )
  on conflict (id) do update
    set display_name = excluded.display_name,
        updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.muller_handle_new_user();

-- ------------------------------
-- Liga semanal
-- ------------------------------
create table if not exists public.league_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users on delete cascade,
  week_key text not null,
  score int not null default 0,
  display_name text,
  updated_at timestamptz default now(),
  unique (user_id, week_key)
);

create index if not exists league_scores_week_score_idx
  on public.league_scores (week_key, score desc);

alter table public.league_scores enable row level security;

drop policy if exists "league_select_all" on public.league_scores;
create policy "league_select_all"
  on public.league_scores for select
  using (true);

drop policy if exists "league_insert_own" on public.league_scores;
create policy "league_insert_own"
  on public.league_scores for insert
  with check ((select auth.uid()) = user_id);

drop policy if exists "league_update_own" on public.league_scores;
create policy "league_update_own"
  on public.league_scores for update
  using ((select auth.uid()) = user_id);

-- ------------------------------
-- Economía segura (anti-trampa base)
-- ------------------------------
create table if not exists public.muller_wallets (
  user_id uuid primary key references auth.users on delete cascade,
  coins bigint not null default 0,
  updated_at timestamptz default now()
);

create table if not exists public.muller_reward_claims (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users on delete cascade,
  reward_type text not null,
  day_key text not null,
  claim_count int not null default 1,
  last_claim_at timestamptz not null default now(),
  unique (user_id, reward_type, day_key)
);

create index if not exists muller_reward_claims_user_day_idx
  on public.muller_reward_claims (user_id, day_key);

-- Lista de creadores con ventajas (solo SQL manual / service role)
create table if not exists public.muller_creator_accounts (
  user_id uuid primary key references auth.users on delete cascade,
  note text,
  created_at timestamptz default now()
);

alter table public.muller_wallets enable row level security;
alter table public.muller_reward_claims enable row level security;
alter table public.muller_creator_accounts enable row level security;

drop policy if exists "wallet_select_own" on public.muller_wallets;
create policy "wallet_select_own"
  on public.muller_wallets for select
  using ((select auth.uid()) = user_id);

drop policy if exists "claims_select_own" on public.muller_reward_claims;
create policy "claims_select_own"
  on public.muller_reward_claims for select
  using ((select auth.uid()) = user_id);

drop policy if exists "creator_select_own" on public.muller_creator_accounts;
create policy "creator_select_own"
  on public.muller_creator_accounts for select
  using ((select auth.uid()) = user_id);

create or replace function public.muller_is_creator(p_user uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists(select 1 from public.muller_creator_accounts c where c.user_id = p_user);
$$;

create or replace function public.muller_get_wallet()
returns table (coins bigint, is_creator boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid;
  v_is_creator boolean := false;
  v_coins bigint := 0;
begin
  v_uid := auth.uid();
  if v_uid is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;

  insert into public.muller_wallets (user_id, coins, updated_at)
  values (v_uid, 0, now())
  on conflict (user_id) do nothing;

  v_is_creator := public.muller_is_creator(v_uid);
  if v_is_creator then
    v_coins := 999999999;
  else
    select w.coins into v_coins from public.muller_wallets w where w.user_id = v_uid;
    v_coins := coalesce(v_coins, 0);
  end if;

  return query select v_coins, v_is_creator;
end;
$$;

create or replace function public.muller_claim_reward(p_reward_type text)
returns table (granted int, balance bigint, reason text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid;
  v_is_creator boolean := false;
  v_day text := to_char(now(), 'YYYY-MM-DD');
  v_now timestamptz := now();
  v_granted int := 0;
  v_balance bigint := 0;
  v_reason text := 'ok';
  v_claim_count int := 0;
  v_last_claim timestamptz := null;
begin
  v_uid := auth.uid();
  if v_uid is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;

  insert into public.muller_wallets (user_id, coins, updated_at)
  values (v_uid, 0, now())
  on conflict (user_id) do nothing;

  v_is_creator := public.muller_is_creator(v_uid);
  if v_is_creator then
    return query select 0, 999999999::bigint, 'creator_unlimited';
    return;
  end if;

  if p_reward_type not in ('daily_bonus', 'ad_reward') then
    return query select 0, (select coins from public.muller_wallets where user_id = v_uid), 'invalid_reward_type';
    return;
  end if;

  select claim_count, last_claim_at
    into v_claim_count, v_last_claim
    from public.muller_reward_claims
    where user_id = v_uid and reward_type = p_reward_type and day_key = v_day;

  v_claim_count := coalesce(v_claim_count, 0);

  if p_reward_type = 'daily_bonus' then
    if v_claim_count >= 1 then
      v_reason := 'already_claimed_today';
    else
      v_granted := 40;
    end if;
  elsif p_reward_type = 'ad_reward' then
    if v_claim_count >= 6 then
      v_reason := 'daily_limit_reached';
    elsif v_last_claim is not null and v_last_claim > (v_now - interval '15 minutes') then
      v_reason := 'cooldown_15m';
    else
      v_granted := 18;
    end if;
  end if;

  if v_granted > 0 then
    update public.muller_wallets
      set coins = coins + v_granted,
          updated_at = v_now
      where user_id = v_uid
      returning coins into v_balance;

    insert into public.muller_reward_claims (user_id, reward_type, day_key, claim_count, last_claim_at)
    values (v_uid, p_reward_type, v_day, 1, v_now)
    on conflict (user_id, reward_type, day_key)
    do update set claim_count = public.muller_reward_claims.claim_count + 1,
                  last_claim_at = excluded.last_claim_at;
    v_reason := 'ok';
  else
    select coins into v_balance from public.muller_wallets where user_id = v_uid;
  end if;

  return query select v_granted, coalesce(v_balance, 0), v_reason;
end;
$$;

create or replace function public.muller_spend_coins(p_amount int, p_reason text default 'spend')
returns table (ok boolean, balance bigint, reason text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid;
  v_is_creator boolean := false;
  v_balance bigint := 0;
begin
  v_uid := auth.uid();
  if v_uid is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;

  if p_amount is null or p_amount <= 0 then
    return query select false, 0::bigint, 'invalid_amount';
    return;
  end if;

  insert into public.muller_wallets (user_id, coins, updated_at)
  values (v_uid, 0, now())
  on conflict (user_id) do nothing;

  v_is_creator := public.muller_is_creator(v_uid);
  if v_is_creator then
    return query select true, 999999999::bigint, 'creator_unlimited';
    return;
  end if;

  update public.muller_wallets
    set coins = coins - p_amount,
        updated_at = now()
    where user_id = v_uid
      and coins >= p_amount
    returning coins into v_balance;

  if v_balance is null then
    select coins into v_balance from public.muller_wallets where user_id = v_uid;
    return query select false, coalesce(v_balance, 0), 'insufficient_coins';
    return;
  end if;

  return query select true, v_balance, coalesce(p_reason, 'ok');
end;
$$;

create or replace function public.muller_submit_league_score(p_week_key text, p_score int, p_display_name text)
returns table (saved_score int)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid;
  v_score int;
begin
  v_uid := auth.uid();
  if v_uid is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;

  v_score := greatest(0, least(coalesce(p_score, 0), 50000));

  insert into public.league_scores (user_id, week_key, score, display_name, updated_at)
  values (v_uid, coalesce(p_week_key, to_char(now(), 'YYYY-MM-DD')), v_score, left(coalesce(p_display_name, 'Estudiante'), 80), now())
  on conflict (user_id, week_key)
  do update set score = greatest(public.league_scores.score, excluded.score),
                display_name = excluded.display_name,
                updated_at = now();

  return query
    select score from public.league_scores where user_id = v_uid and week_key = coalesce(p_week_key, to_char(now(), 'YYYY-MM-DD'));
end;
$$;
-- Müller App · Supabase (plan gratuito)
-- Ejecuta esto en: SQL Editor → New query → Run
-- Auth: Authentication → Providers → Email → puedes desactivar "Confirm email" para pruebas locales.

-- Perfiles públicos (lectura para todos los usuarios autenticados / anon según políticas)
create table if not exists public.profiles (
  id uuid primary key references auth.users on delete cascade,
  display_name text,
  updated_at timestamptz default now()
);

alter table public.profiles enable row level security;

drop policy if exists "profiles_select_all" on public.profiles;
create policy "profiles_select_all"
  on public.profiles for select
  using (true);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
  on public.profiles for insert
  with check ((select auth.uid()) = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles for update
  using ((select auth.uid()) = id);

-- Perfil al registrarse (metadata display_name desde la app)
create or replace function public.muller_handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name, updated_at)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'display_name', 'Estudiante'),
    now()
  )
  on conflict (id) do update
    set display_name = excluded.display_name,
        updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.muller_handle_new_user();

-- Liga semanal: una fila por usuario y semana (week_key = lunes ISO YYYY-MM-DD)
create table if not exists public.league_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users on delete cascade,
  week_key text not null,
  score int not null default 0,
  display_name text,
  updated_at timestamptz default now(),
  unique (user_id, week_key)
);

create index if not exists league_scores_week_score_idx
  on public.league_scores (week_key, score desc);

alter table public.league_scores enable row level security;

drop policy if exists "league_select_all" on public.league_scores;
create policy "league_select_all"
  on public.league_scores for select
  using (true);

drop policy if exists "league_insert_own" on public.league_scores;
create policy "league_insert_own"
  on public.league_scores for insert
  with check ((select auth.uid()) = user_id);

drop policy if exists "league_update_own" on public.league_scores;
create policy "league_update_own"
  on public.league_scores for update
  using ((select auth.uid()) = user_id);
